name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create artifact
        run: zip -r artifact.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-server
          path: artifact.zip

      - name: Give execution permission
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        run: npm test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/jest/junit.xml # Вкажіть шлях до звіту

      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Jest Tests
          path: reports/jest/junit.xml
          reporter: jest-junit