name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Вкажіть вашу версію Node.js

      - name: Install dependencies
        run: npm install

      - name: Create artifact
        run: zip -r my-express-app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-express-app
          path: my-express-app.zip