name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Вкажіть вашу версію Node.js

      - name: Install dependencies
        run: npm install

      - name: Create artifact
        run: zip -r artifact.zip . -x "node_modules"        
         # Змініть на ваш шлях до артефакту

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-server
          path: artifact.zip